---
- name: Install Docker.io in Debian/Ubuntu
  apt:
    name: docker.io
    state: present
    force_apt_get: True
  when: ansible_facts['os_family'] == "Debian"

- name: Enable Docker - systemd
  systemd:
    name: docker
    state: restarted
    enabled: yes
  when: ansible_facts['os_family'] == "Debian"
