---
# Include for RedHat based
- name: Show Ansible Distro
  debug:
    msg: "Distro: {{ ansible_distribution }}"

- name: Install dnf-plugins-core
  become: yes
  yum:
    name: dnf-plugins-core
    state: present
  when: ansible_facts['os_family'] == "RedHat" 

- name: Add Docker DNF Repo (Fedora)
  become: yes
  yum_repository:
    name: Docker.io
    description: Docker CE repo
    baseurl: https://download.docker.com/linux/fedora/34/x86_64/stable/
    gpgcheck: no
  when: ansible_distribution == "Fedora"

- name: Add Docker DNF Repo (CentOS 8)
  become: yes
  yum_repository:
    name: Docker.io
    description: Docker CE repo
    baseurl: https://download.docker.com/linux/centos/8/x86_64/stable/
    gpgcheck: no
  when: ansible_distribution == "CentOS"

- name: Install Docker (RPM)
  become: yes
  yum:
    name: docker-ce,containerd.io
    state: present
  when: ansible_facts['os_family'] == "RedHat" 

- name: Enable Docker - systemd
  become: yes
  systemd:
    name: docker
    state: restarted
    enabled: yes
  when: ansible_facts['os_family'] == "RedHat"
