---
# tasks file for updates

- name: Update APT
  apt:
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Update OS
  apt:
    name: '*'
    state: latest
    force_apt_get: True
  when: ansible_facts['os_family'] == "Debian"

- name: Install required packages (dependencies)
  apt:
    name: gnupg,software-properties-common,curl
    state: latest
    force_apt_get: True
  when: ansible_facts['os_family'] == "Debian"

- name: Add Terraform repository
  shell: 
    #!/bin/bash
    curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
    apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
  when: ansible_facts['os_family'] == "Debian"

- name: Add MS PowerShell Repo Debian
  get_url:
    url: https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb
    dest: /tmp
  when: ansible_distribution == "Debian"

- name: Add MS PowerShell Repo Ubuntu
  get_url:
    url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
    dest: /tmp
  when: ansible_distribution == "Ubuntu"

- name: Install Required Repos
  apt: deb="/tmp/packages-microsoft-prod.deb"
  when: ansible_facts['os_family'] == "Debian"

- name: Update APT
  apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Enable universe repo
  command: add-apt-repository universe
  when: ansible_distribution == "Ubuntu"

- name: Install Azure CLI (Debian/Ubuntu)
  shell: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash 
  when: ansible_facts['os_family'] == "Debian"

- name: Update APT
  apt:
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Install Git Zip, Unzip, Ansible, PowerShell, Azure-CLI and Terraform
  apt:
    name: git, ansible, terraform, powershell, zip, unzip
    state: latest
    force_apt_get: True
  when: ansible_facts['os_family'] == "Debian"

