---
# tasks file for updates

- name: Update MOTD
  become: yes
  copy:
    src: motd
    dest: /etc/motd

- name: Update OS
  become: yes
  dnf:
    name: '*'
    state: latest

- name: Add Terraform repository
  become: yes
  shell: dnf config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: Add MS PowerShell Repo
  become: yes
  get_url:
    url: https://packages.microsoft.com/config/rhel/8/prod.repo
    dest: /etc/yum.repos.d/microsoft.repo

- name: Install Ansible Repo on CentOS 8
  become: yes
  dnf:
    name: centos-release-ansible-29
    state: latest

- name: Import Azure CLI RPM key
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Add MS Azure CLI Repo
  become: yes
  get_url:
    url: https://gist.githubusercontent.com/fabiansald/0a266a536284a2b1e0e35af25e31fb50/raw/ff1ad7aa33a60657750c0ef4852bba76bddfc17a/azure-cli.repo
    dest: /etc/yum.repos.d/azure-cli.repo

- name: Install Git Zip, Unzip, Ansible, PowerShell, Azure-CLI and Terraform
  become: yes
  dnf:
    name: git, ansible, terraform, powershell, azure-cli, zip, unzip
    state: latest

- name: Install PowerShell Azure Module
  shell: Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force
  args:
    executable: "/usr/bin/pwsh"
  register: result

#- name: Show PowerShell Azure Module output
#  debug:
#    msg: "{{ result }}"
