---
# tasks file for updates

- name: Update MOTD
  copy:
    src: motd
    dest: /etc/motd

- include: rpmbased.yml
  when: ansible_facts['os_family'] == "RedHat"

- include: debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Install PowerShell Azure Module
  remote_user: "{{ ansible_user }}"
  shell: Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force
  args:
    executable: "/usr/bin/pwsh"
  register: result
